# This file defines the the ci pipelines that are run in gitlab every time a commit is pushed.

stages:
    - pre-commit

pre-commit:
    stage: pre-commit
    image: python:3.12
    before_script:
        - pip install pre-commit
        - pre-commit install

        - python3 -m venv .venv
        - source .venv/bin/activate
        - pip install poetry
        - poetry install
    script:
        - pre-commit run --all-files
    allow_failure: false